# Generated by Django 5.2.4 on 2025-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='image_url',
        ),
        migrations.AddField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='best_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='poster',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='color_theme',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='format',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poster',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='style',
            field=models.CharField(max_length=50),
        ),
    ]
