# Generated by Django 5.2.4 on 2025-08-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_poster_image_url_poster_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='best_time',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='color_theme',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='format',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='style',
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_posters/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
