# Generated by Django 5.2.4 on 2025-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_poster_best_time_remove_poster_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='design_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
