# Generated by Django 5.2.4 on 2025-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_poster_design_style_poster_industry_poster_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
