# Generated by Django 5.2.4 on 2025-08-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_poster_caption_poster_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='hashtags',
        ),
    ]
