# Generated by Django 5.2.4 on 2025-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_remove_poster_caption_remove_poster_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='public_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
