# Generated by Django 5.2.4 on 2025-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='caption',
        ),
        migrations.AddField(
            model_name='poster',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
