# Generated by Django 5.2.4 on 2025-08-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_remove_socialaccount_caption_poster_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='page_id',
            new_name='fb_page_id',
        ),
    ]
