# Generated by Django 5.2.4 on 2025-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_rename_page_id_socialaccount_fb_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
