# Generated by Django 5.2.4 on 2025-08-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_alter_socialaccount_fb_page_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
