# Generated by Django 5.2.4 on 2025-08-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
